#!/bin/bash

echo "=== Testing Stock Requisition Page (Logged In) ==="
echo ""
echo "Since the page requires authentication, you need to:"
echo ""
echo "1. Open your browser and login to: https://pryro.eastgatehotel.rw"
echo ""
echo "2. After login, press F12 to open DevTools"
echo ""
echo "3. Go to Console tab and run these commands:"
echo ""
echo "   // Check what component is loaded"
echo "   console.log('Component:', window.page?.component)"
echo ""
echo "   // Check if props are passed"
echo "   console.log('Props:', window.page?.props)"
echo ""
echo "   // Check requisitions data"
echo "   console.log('Requisitions:', window.page?.props?.requisitions)"
echo ""
echo "4. Navigate to: https://pryro.eastgatehotel.rw/stock-requisitions"
echo ""
echo "5. In Console, check again:"
echo "   window.page.component"
echo ""
echo "   Expected output: 'StockRequisition/StockRequisitions/Index'"
echo ""
echo "6. If you see the component name but no buttons, check Network tab:"
echo "   - Filter by 'JS'"
echo "   - Look for 'Index-C-x4p8Px.js'"
echo "   - Check if it loads (Status should be 200)"
echo "   - If Status is 304 (cached), that's the problem!"
echo ""
echo "7. To fix cache issue:"
echo "   - Press Ctrl+Shift+R (Windows/Linux) or Cmd+Shift+R (Mac)"
echo "   - Or right-click refresh → 'Empty Cache and Hard Reload'"
echo ""
echo "8. Alternative: Test in Incognito mode"
echo "   - Open new incognito/private window"
echo "   - Login again"
echo "   - Navigate to stock-requisitions"
echo "   - This bypasses all cache"
echo ""
echo "=== Server-Side Cache Clear ==="
echo ""
echo "Running Laravel cache clear..."
php artisan cache:clear
php artisan config:clear  
php artisan route:clear
php artisan view:clear

echo ""
echo "✓ Server caches cleared"
echo ""
echo "Now clear your BROWSER cache and test again!"
echo ""
